
/*
	File Generated by NetTiers templates [www.nettiers.com]
	Generated on : Monday, May 02, 2011
	Important: Do not modify this file. Edit the file SqlProjectPhaseProvider.cs instead.
*/

#region using directives

using System;
using System.Data;
using System.Data.Common;
using System.Text;

using Microsoft.Practices.EnterpriseLibrary.Data;
using Microsoft.Practices.EnterpriseLibrary.Data.Sql;

using System.Collections;
using System.Collections.Specialized;

using System.Diagnostics;
using RLM.Construction.Entities;
using RLM.Construction.Data;
using RLM.Construction.Data.Bases;

#endregion

namespace RLM.Construction.Data.SqlClient
{
	///<summary>
	/// This class is the SqlClient Data Access Logic Component implementation for the <see cref="ProjectPhase"/> entity.
	///</summary>
	public partial class SqlProjectPhaseProviderBase : ProjectPhaseProviderBase
	{
		#region Declarations
		
		string _connectionString;
	    bool _useStoredProcedure;
	    string _providerInvariantName;
			
		#endregion "Declarations"
			
		#region Constructors
		
		/// <summary>
		/// Creates a new <see cref="SqlProjectPhaseProviderBase"/> instance.
		/// </summary>
		public SqlProjectPhaseProviderBase()
		{
		}
	
	/// <summary>
	/// Creates a new <see cref="SqlProjectPhaseProviderBase"/> instance.
	/// Uses connection string to connect to datasource.
	/// </summary>
	/// <param name="connectionString">The connection string to the database.</param>
	/// <param name="useStoredProcedure">A boolean value that indicates if we use the stored procedures or embedded queries.</param>
	/// <param name="providerInvariantName">Name of the invariant provider use by the DbProviderFactory.</param>
	public SqlProjectPhaseProviderBase(string connectionString, bool useStoredProcedure, string providerInvariantName)
	{
		this._connectionString = connectionString;
		this._useStoredProcedure = useStoredProcedure;
		this._providerInvariantName = providerInvariantName;
	}
		
	#endregion "Constructors"
	
		#region Public properties
	/// <summary>
    /// Gets or sets the connection string.
    /// </summary>
    /// <value>The connection string.</value>
    public string ConnectionString
	{
		get {return this._connectionString;}
		set {this._connectionString = value;}
	}
	
	/// <summary>
    /// Gets or sets a value indicating whether to use stored procedures.
    /// </summary>
    /// <value><c>true</c> if we choose to use use stored procedures; otherwise, <c>false</c>.</value>
	public bool UseStoredProcedure
	{
		get {return this._useStoredProcedure;}
		set {this._useStoredProcedure = value;}
	}
	
	/// <summary>
    /// Gets or sets the invariant provider name listed in the DbProviderFactories machine.config section.
    /// </summary>
    /// <value>The name of the provider invariant.</value>
    public string ProviderInvariantName
    {
        get { return this._providerInvariantName; }
        set { this._providerInvariantName = value; }
    }
	#endregion
	
		#region Get Many To Many Relationship Functions
		#endregion
	
		#region Delete Functions
		/// <summary>
		/// 	Deletes a row from the DataSource.
		/// </summary>
		/// <param name="projectPhaseId">. Primary Key.</param>	
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks>Deletes based on primary key(s).</remarks>
		/// <returns>Returns true if operation suceeded.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Delete(TransactionManager transactionManager, System.Int32 projectPhaseId)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_Delete", _useStoredProcedure);
			database.AddInParameter(commandWrapper, "@ProjectPhaseId", DbType.Int32, projectPhaseId);
			
			int results = 0;
			
			if (transactionManager != null)
			{	
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
			{
				string entityKey = EntityLocator.ConstructKeyFromPkItems(typeof(ProjectPhase)
					,projectPhaseId);
				EntityManager.StopTracking(entityKey);
			}
			
			if (results == 0)
			{
				//throw new DataException("The record has been already deleted.");
				return false;
			}
			
			return Convert.ToBoolean(results);
		}//end Delete
		#endregion

		#region Find Functions

		#region Parsed Find Methods
		/// <summary>
		/// 	Returns rows meeting the whereclause condition from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks>Operators must be capitalized (OR, AND)</remarks>
		/// <returns>Returns a typed collection of RLM.Construction.Entities.ProjectPhase objects.</returns>
		public override RLM.Construction.Entities.TList<ProjectPhase> Find(TransactionManager transactionManager, string whereClause, int start, int pageLength, out int count)
		{
			count = -1;
			if (whereClause.IndexOf(";") > -1)
				return new RLM.Construction.Entities.TList<ProjectPhase>();
	
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_Find", _useStoredProcedure);

		bool searchUsingOR = false;
		if (whereClause.IndexOf(" OR ") > 0) // did they want to do "a=b OR c=d OR..."?
			searchUsingOR = true;
		
		database.AddInParameter(commandWrapper, "@SearchUsingOR", DbType.Boolean, searchUsingOR);
		
		database.AddInParameter(commandWrapper, "@ProjectPhaseId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ParentProjectPhaseId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ProjectId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ContractId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ManagerId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@CurrencyUnitId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Name", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Description", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@DesignPrice", DbType.Currency, DBNull.Value);
		database.AddInParameter(commandWrapper, "@AuctualPrice", DbType.Currency, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsActive", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsApprove", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsCurrentProjectPhase", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Status", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@Type", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@FromDate", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ToDate", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@RealFromDate", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@RealToDate", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ParentPath", DbType.String, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsCollectItemFromChild", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsStart", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsFinished", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@IsBillable", DbType.Boolean, DBNull.Value);
		database.AddInParameter(commandWrapper, "@CreationDate", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@CreationUserId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@LastModificationDate", DbType.DateTime, DBNull.Value);
		database.AddInParameter(commandWrapper, "@LastModificationUserId", DbType.Int32, DBNull.Value);
		database.AddInParameter(commandWrapper, "@ExchangeRate", DbType.Int32, DBNull.Value);
	
			// replace all instances of 'AND' and 'OR' because we already set searchUsingOR
			whereClause = whereClause.Replace(" AND ", "|").Replace(" OR ", "|") ; 
			string[] clauses = whereClause.ToLower().Split('|');
		
			// Here's what's going on below: Find a field, then to get the value we
			// drop the field name from the front, trim spaces, drop the '=' sign,
			// trim more spaces, and drop any outer single quotes.
			// Now handles the case when two fields start off the same way - like "Friendly='Yes' AND Friend='john'"
				
			char[] equalSign = {'='};
			char[] singleQuote = {'\''};
	   		foreach (string clause in clauses)
			{
				if (clause.Trim().StartsWith("projectphaseid ") || clause.Trim().StartsWith("projectphaseid="))
				{
					database.SetParameterValue(commandWrapper, "@ProjectPhaseId", 
						clause.Replace("projectphaseid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("parentprojectphaseid ") || clause.Trim().StartsWith("parentprojectphaseid="))
				{
					database.SetParameterValue(commandWrapper, "@ParentProjectPhaseId", 
						clause.Replace("parentprojectphaseid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("projectid ") || clause.Trim().StartsWith("projectid="))
				{
					database.SetParameterValue(commandWrapper, "@ProjectId", 
						clause.Replace("projectid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("contractid ") || clause.Trim().StartsWith("contractid="))
				{
					database.SetParameterValue(commandWrapper, "@ContractId", 
						clause.Replace("contractid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("managerid ") || clause.Trim().StartsWith("managerid="))
				{
					database.SetParameterValue(commandWrapper, "@ManagerId", 
						clause.Replace("managerid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("currencyunitid ") || clause.Trim().StartsWith("currencyunitid="))
				{
					database.SetParameterValue(commandWrapper, "@CurrencyUnitId", 
						clause.Replace("currencyunitid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("name ") || clause.Trim().StartsWith("name="))
				{
					database.SetParameterValue(commandWrapper, "@Name", 
						clause.Replace("name","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("description ") || clause.Trim().StartsWith("description="))
				{
					database.SetParameterValue(commandWrapper, "@Description", 
						clause.Replace("description","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("designprice ") || clause.Trim().StartsWith("designprice="))
				{
					database.SetParameterValue(commandWrapper, "@DesignPrice", 
						clause.Replace("designprice","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("auctualprice ") || clause.Trim().StartsWith("auctualprice="))
				{
					database.SetParameterValue(commandWrapper, "@AuctualPrice", 
						clause.Replace("auctualprice","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isactive ") || clause.Trim().StartsWith("isactive="))
				{
					database.SetParameterValue(commandWrapper, "@IsActive", 
						clause.Replace("isactive","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isapprove ") || clause.Trim().StartsWith("isapprove="))
				{
					database.SetParameterValue(commandWrapper, "@IsApprove", 
						clause.Replace("isapprove","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("iscurrentprojectphase ") || clause.Trim().StartsWith("iscurrentprojectphase="))
				{
					database.SetParameterValue(commandWrapper, "@IsCurrentProjectPhase", 
						clause.Replace("iscurrentprojectphase","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("status ") || clause.Trim().StartsWith("status="))
				{
					database.SetParameterValue(commandWrapper, "@Status", 
						clause.Replace("status","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("type ") || clause.Trim().StartsWith("type="))
				{
					database.SetParameterValue(commandWrapper, "@Type", 
						clause.Replace("type","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("fromdate ") || clause.Trim().StartsWith("fromdate="))
				{
					database.SetParameterValue(commandWrapper, "@FromDate", 
						clause.Replace("fromdate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("todate ") || clause.Trim().StartsWith("todate="))
				{
					database.SetParameterValue(commandWrapper, "@ToDate", 
						clause.Replace("todate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("realfromdate ") || clause.Trim().StartsWith("realfromdate="))
				{
					database.SetParameterValue(commandWrapper, "@RealFromDate", 
						clause.Replace("realfromdate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("realtodate ") || clause.Trim().StartsWith("realtodate="))
				{
					database.SetParameterValue(commandWrapper, "@RealToDate", 
						clause.Replace("realtodate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("parentpath ") || clause.Trim().StartsWith("parentpath="))
				{
					database.SetParameterValue(commandWrapper, "@ParentPath", 
						clause.Replace("parentpath","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("iscollectitemfromchild ") || clause.Trim().StartsWith("iscollectitemfromchild="))
				{
					database.SetParameterValue(commandWrapper, "@IsCollectItemFromChild", 
						clause.Replace("iscollectitemfromchild","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isstart ") || clause.Trim().StartsWith("isstart="))
				{
					database.SetParameterValue(commandWrapper, "@IsStart", 
						clause.Replace("isstart","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isfinished ") || clause.Trim().StartsWith("isfinished="))
				{
					database.SetParameterValue(commandWrapper, "@IsFinished", 
						clause.Replace("isfinished","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("isbillable ") || clause.Trim().StartsWith("isbillable="))
				{
					database.SetParameterValue(commandWrapper, "@IsBillable", 
						clause.Replace("isbillable","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("creationdate ") || clause.Trim().StartsWith("creationdate="))
				{
					database.SetParameterValue(commandWrapper, "@CreationDate", 
						clause.Replace("creationdate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("creationuserid ") || clause.Trim().StartsWith("creationuserid="))
				{
					database.SetParameterValue(commandWrapper, "@CreationUserId", 
						clause.Replace("creationuserid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("lastmodificationdate ") || clause.Trim().StartsWith("lastmodificationdate="))
				{
					database.SetParameterValue(commandWrapper, "@LastModificationDate", 
						clause.Replace("lastmodificationdate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("lastmodificationuserid ") || clause.Trim().StartsWith("lastmodificationuserid="))
				{
					database.SetParameterValue(commandWrapper, "@LastModificationUserId", 
						clause.Replace("lastmodificationuserid","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
				if (clause.Trim().StartsWith("exchangerate ") || clause.Trim().StartsWith("exchangerate="))
				{
					database.SetParameterValue(commandWrapper, "@ExchangeRate", 
						clause.Replace("exchangerate","").Trim().TrimStart(equalSign).Trim().Trim(singleQuote));
					continue;
				}
	
				throw new ArgumentException("Unable to use this part of the where clause in this version of Find: " + clause);
			}
					
			IDataReader reader = null;
			//Create Collection
			RLM.Construction.Entities.TList<ProjectPhase> rows = new RLM.Construction.Entities.TList<ProjectPhase>();
	
				
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
				
				Fill(reader, rows, start, pageLength);
				
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if (reader != null) 
					reader.Close();				
			}
			return rows;
		}

		#endregion Parsed Find Methods
		
		#region Parameterized Find Methods
		
		/// <summary>
		/// 	Returns rows from the DataSource that meet the parameter conditions.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="parameters">A collection of <see cref="SqlFilterParameter"/> objects.</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <returns>Returns a typed collection of RLM.Construction.Entities.ProjectPhase objects.</returns>
		public override RLM.Construction.Entities.TList<ProjectPhase> Find(TransactionManager transactionManager, SqlFilterParameterCollection parameters, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_Find_Dynamic", typeof(ProjectPhaseColumn), parameters, orderBy, start, pageLength);
			
			if ( parameters != null )
			{
				SqlFilterParameter param;

				for ( int i = 0; i < parameters.Count; i++ )
				{
					param = parameters[i];
					database.AddInParameter(commandWrapper, param.Name, param.DbType, param.Value);
				}
			}

			RLM.Construction.Entities.TList<ProjectPhase> rows = new RLM.Construction.Entities.TList<ProjectPhase>();
			IDataReader reader = null;
			
			try
			{
				if ( transactionManager != null )
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;
				
				if ( reader.NextResult() )
				{
					if ( reader.Read() )
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if ( reader != null )
					reader.Close();
			}
			
			return rows;
		}
		
		#endregion Parameterized Find Methods
		
		#endregion Find Functions
	
		#region GetAll Methods
				
		/// <summary>
		/// 	Gets All rows from the DataSource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out. The number of rows that match this query.</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of RLM.Construction.Entities.ProjectPhase objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override RLM.Construction.Entities.TList<ProjectPhase> GetAll(TransactionManager transactionManager, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_Get_List", _useStoredProcedure);
			
			IDataReader reader = null;
		
			//Create Collection
			RLM.Construction.Entities.TList<ProjectPhase> rows = new RLM.Construction.Entities.TList<ProjectPhase>();
			
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
			}
			return rows;
		}//end getall
		
		#endregion
				
		#region GetPaged Methods
				
		/// <summary>
		/// Gets a page of rows from the DataSource.
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">Number of rows in the DataSource.</param>
		/// <param name="whereClause">Specifies the condition for the rows returned by a query (Name='John Doe', Name='John Doe' AND Id='1', Name='John Doe' OR Id='1').</param>
		/// <param name="orderBy">Specifies the sort criteria for the rows in the DataSource (Name ASC; BirthDay DESC, Name ASC);</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of RLM.Construction.Entities.ProjectPhase objects.</returns>
		public override RLM.Construction.Entities.TList<ProjectPhase> GetPaged(TransactionManager transactionManager, string whereClause, string orderBy, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_GetPaged", _useStoredProcedure);
			
			database.AddInParameter(commandWrapper, "@WhereClause", DbType.String, whereClause);
			database.AddInParameter(commandWrapper, "@OrderBy", DbType.String, orderBy);
			database.AddInParameter(commandWrapper, "@PageIndex", DbType.Int32, start);
			database.AddInParameter(commandWrapper, "@PageSize", DbType.Int32, pageLength);
		
			IDataReader reader = null;
			//Create Collection
			RLM.Construction.Entities.TList<ProjectPhase> rows = new RLM.Construction.Entities.TList<ProjectPhase>();
			
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
				
				Fill(reader, rows, 0, int.MaxValue);
				count = rows.Count;

				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			catch(Exception)
			{			
				throw;
			}
			finally
			{
				if (reader != null) 
					reader.Close();
			}
			
			return rows;
		}
		
		#endregion	
		
		#region Get By Foreign Key Functions

		#region GetByProjectId
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_ProjectPhase_Project key.
		///		FK_ProjectPhase_Project Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="projectId"></param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of RLM.Construction.Entities.ProjectPhase objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override RLM.Construction.Entities.TList<ProjectPhase> GetByProjectId(TransactionManager transactionManager, System.Int32 projectId, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_GetByProjectId", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@ProjectId", DbType.Int32, projectId);
			
			IDataReader reader = null;
			RLM.Construction.Entities.TList<ProjectPhase> rows = new RLM.Construction.Entities.TList<ProjectPhase>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
			
				//Create Collection
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if (reader != null) 
					reader.Close();
			}
			return rows;
		}	
		#endregion
	

		#region GetByContractId
		/// <summary>
		/// 	Gets rows from the datasource based on the FK_ProjectPhase_Contract key.
		///		FK_ProjectPhase_Contract Description: 
		/// </summary>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="contractId"></param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <remarks></remarks>
		/// <returns>Returns a typed collection of RLM.Construction.Entities.ProjectPhase objects.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override RLM.Construction.Entities.TList<ProjectPhase> GetByContractId(TransactionManager transactionManager, System.Int32? contractId, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_GetByContractId", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@ContractId", DbType.Int32, contractId);
			
			IDataReader reader = null;
			RLM.Construction.Entities.TList<ProjectPhase> rows = new RLM.Construction.Entities.TList<ProjectPhase>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}
			
				//Create Collection
				Fill(reader, rows, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally
			{
				if (reader != null) 
					reader.Close();
			}
			return rows;
		}	
		#endregion
	
	#endregion
	
		#region Get By Index Functions

		#region GetByProjectPhaseId
					
		/// <summary>
		/// 	Gets rows from the datasource based on the PK_ProjectPhase index.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="projectPhaseId"></param>
		/// <param name="start">Row number at which to start reading.</param>
		/// <param name="pageLength">Number of rows to return.</param>
		/// <param name="count">out parameter to get total records for query</param>
		/// <returns>Returns an instance of the <see cref="RLM.Construction.Entities.ProjectPhase"/> class.</returns>
		/// <remarks></remarks>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override RLM.Construction.Entities.ProjectPhase GetByProjectPhaseId(TransactionManager transactionManager, System.Int32 projectPhaseId, int start, int pageLength, out int count)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_GetByProjectPhaseId", _useStoredProcedure);
			
				database.AddInParameter(commandWrapper, "@ProjectPhaseId", DbType.Int32, projectPhaseId);
			
			IDataReader reader = null;
			RLM.Construction.Entities.TList<ProjectPhase> tmp = new RLM.Construction.Entities.TList<ProjectPhase>();
			try
			{
				if (transactionManager != null)
				{
					reader = Utility.ExecuteReader(transactionManager, commandWrapper);
				}
				else
				{
					reader = Utility.ExecuteReader(database, commandWrapper);
				}		
		
				//Create collection and fill
				Fill(reader, tmp, start, pageLength);
				count = -1;
				if(reader.NextResult())
				{
					if(reader.Read())
					{
						count = reader.GetInt32(0);
					}
				}
			}
			finally 
			{
				if (reader != null) 
					reader.Close();
			}
			
			if (tmp.Count == 1)
			{
				return tmp[0];
			}
			else if (tmp.Count == 0)
			{
				return null;
			}
			else
			{
				throw new DataException("Cannot find the unique instance of the class.");
			}
			
			//return rows;
		}
		
		#endregion

	#endregion Get By Index Functions

		#region Insert Methods
		/// <summary>
		/// Lets you efficiently bulk many entity to the database.
		/// </summary>
		/// <param name="transactionManager">The transaction manager.</param>
		/// <param name="entities">The entities.</param>
		/// <remarks>
		///		After inserting into the datasource, the RLM.Construction.Entities.ProjectPhase object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		public override void BulkInsert(TransactionManager transactionManager, TList<RLM.Construction.Entities.ProjectPhase> entities)
		{
			//System.Data.SqlClient.SqlBulkCopy bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			
			System.Data.SqlClient.SqlBulkCopy bulkCopy = null;
	
			if (transactionManager != null && transactionManager.IsOpen)
			{			
				System.Data.SqlClient.SqlConnection cnx = transactionManager.TransactionObject.Connection as System.Data.SqlClient.SqlConnection;
				System.Data.SqlClient.SqlTransaction transaction = transactionManager.TransactionObject as System.Data.SqlClient.SqlTransaction;
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(cnx, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints, transaction); //, null);
			}
			else
			{
				bulkCopy = new System.Data.SqlClient.SqlBulkCopy(this._connectionString, System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints); //, null);
			}
			
			bulkCopy.BulkCopyTimeout = 360;
			bulkCopy.DestinationTableName = "ProjectPhase";
			
			DataTable dataTable = new DataTable();
			DataColumn col0 = dataTable.Columns.Add("ProjectPhaseId", typeof(System.Int32));
			col0.AllowDBNull = false;		
			DataColumn col1 = dataTable.Columns.Add("ParentProjectPhaseId", typeof(System.Int32));
			col1.AllowDBNull = true;		
			DataColumn col2 = dataTable.Columns.Add("ProjectId", typeof(System.Int32));
			col2.AllowDBNull = false;		
			DataColumn col3 = dataTable.Columns.Add("ContractId", typeof(System.Int32));
			col3.AllowDBNull = true;		
			DataColumn col4 = dataTable.Columns.Add("ManagerId", typeof(System.Int32));
			col4.AllowDBNull = true;		
			DataColumn col5 = dataTable.Columns.Add("CurrencyUnitId", typeof(System.Int32));
			col5.AllowDBNull = true;		
			DataColumn col6 = dataTable.Columns.Add("Name", typeof(System.String));
			col6.AllowDBNull = false;		
			DataColumn col7 = dataTable.Columns.Add("Description", typeof(System.String));
			col7.AllowDBNull = true;		
			DataColumn col8 = dataTable.Columns.Add("DesignPrice", typeof(System.Decimal));
			col8.AllowDBNull = true;		
			DataColumn col9 = dataTable.Columns.Add("AuctualPrice", typeof(System.Decimal));
			col9.AllowDBNull = true;		
			DataColumn col10 = dataTable.Columns.Add("IsActive", typeof(System.Boolean));
			col10.AllowDBNull = true;		
			DataColumn col11 = dataTable.Columns.Add("IsApprove", typeof(System.Boolean));
			col11.AllowDBNull = true;		
			DataColumn col12 = dataTable.Columns.Add("IsCurrentProjectPhase", typeof(System.Boolean));
			col12.AllowDBNull = true;		
			DataColumn col13 = dataTable.Columns.Add("Status", typeof(System.Int32));
			col13.AllowDBNull = true;		
			DataColumn col14 = dataTable.Columns.Add("Type", typeof(System.Int32));
			col14.AllowDBNull = true;		
			DataColumn col15 = dataTable.Columns.Add("FromDate", typeof(System.DateTime));
			col15.AllowDBNull = true;		
			DataColumn col16 = dataTable.Columns.Add("ToDate", typeof(System.DateTime));
			col16.AllowDBNull = true;		
			DataColumn col17 = dataTable.Columns.Add("RealFromDate", typeof(System.DateTime));
			col17.AllowDBNull = true;		
			DataColumn col18 = dataTable.Columns.Add("RealToDate", typeof(System.DateTime));
			col18.AllowDBNull = true;		
			DataColumn col19 = dataTable.Columns.Add("ParentPath", typeof(System.String));
			col19.AllowDBNull = true;		
			DataColumn col20 = dataTable.Columns.Add("IsCollectItemFromChild", typeof(System.Boolean));
			col20.AllowDBNull = true;		
			DataColumn col21 = dataTable.Columns.Add("IsStart", typeof(System.Boolean));
			col21.AllowDBNull = true;		
			DataColumn col22 = dataTable.Columns.Add("IsFinished", typeof(System.Boolean));
			col22.AllowDBNull = true;		
			DataColumn col23 = dataTable.Columns.Add("IsBillable", typeof(System.Boolean));
			col23.AllowDBNull = true;		
			DataColumn col24 = dataTable.Columns.Add("CreationDate", typeof(System.DateTime));
			col24.AllowDBNull = true;		
			DataColumn col25 = dataTable.Columns.Add("CreationUserId", typeof(System.Int32));
			col25.AllowDBNull = true;		
			DataColumn col26 = dataTable.Columns.Add("LastModificationDate", typeof(System.DateTime));
			col26.AllowDBNull = true;		
			DataColumn col27 = dataTable.Columns.Add("LastModificationUserId", typeof(System.Int32));
			col27.AllowDBNull = true;		
			DataColumn col28 = dataTable.Columns.Add("ExchangeRate", typeof(System.Int32));
			col28.AllowDBNull = true;		
			
			bulkCopy.ColumnMappings.Add("ProjectPhaseId", "ProjectPhaseId");
			bulkCopy.ColumnMappings.Add("ParentProjectPhaseId", "ParentProjectPhaseId");
			bulkCopy.ColumnMappings.Add("ProjectId", "ProjectId");
			bulkCopy.ColumnMappings.Add("ContractId", "ContractId");
			bulkCopy.ColumnMappings.Add("ManagerId", "ManagerId");
			bulkCopy.ColumnMappings.Add("CurrencyUnitId", "CurrencyUnitId");
			bulkCopy.ColumnMappings.Add("Name", "Name");
			bulkCopy.ColumnMappings.Add("Description", "Description");
			bulkCopy.ColumnMappings.Add("DesignPrice", "DesignPrice");
			bulkCopy.ColumnMappings.Add("AuctualPrice", "AuctualPrice");
			bulkCopy.ColumnMappings.Add("IsActive", "IsActive");
			bulkCopy.ColumnMappings.Add("IsApprove", "IsApprove");
			bulkCopy.ColumnMappings.Add("IsCurrentProjectPhase", "IsCurrentProjectPhase");
			bulkCopy.ColumnMappings.Add("Status", "Status");
			bulkCopy.ColumnMappings.Add("Type", "Type");
			bulkCopy.ColumnMappings.Add("FromDate", "FromDate");
			bulkCopy.ColumnMappings.Add("ToDate", "ToDate");
			bulkCopy.ColumnMappings.Add("RealFromDate", "RealFromDate");
			bulkCopy.ColumnMappings.Add("RealToDate", "RealToDate");
			bulkCopy.ColumnMappings.Add("ParentPath", "ParentPath");
			bulkCopy.ColumnMappings.Add("IsCollectItemFromChild", "IsCollectItemFromChild");
			bulkCopy.ColumnMappings.Add("IsStart", "IsStart");
			bulkCopy.ColumnMappings.Add("IsFinished", "IsFinished");
			bulkCopy.ColumnMappings.Add("IsBillable", "IsBillable");
			bulkCopy.ColumnMappings.Add("CreationDate", "CreationDate");
			bulkCopy.ColumnMappings.Add("CreationUserId", "CreationUserId");
			bulkCopy.ColumnMappings.Add("LastModificationDate", "LastModificationDate");
			bulkCopy.ColumnMappings.Add("LastModificationUserId", "LastModificationUserId");
			bulkCopy.ColumnMappings.Add("ExchangeRate", "ExchangeRate");
			
			foreach(RLM.Construction.Entities.ProjectPhase entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
					
				DataRow row = dataTable.NewRow();
				
					row["ProjectPhaseId"] = entity.ProjectPhaseId;
							
				
					row["ParentProjectPhaseId"] = entity.ParentProjectPhaseId.HasValue ? (object) entity.ParentProjectPhaseId  : System.DBNull.Value;
							
				
					row["ProjectId"] = entity.ProjectId;
							
				
					row["ContractId"] = entity.ContractId.HasValue ? (object) entity.ContractId  : System.DBNull.Value;
							
				
					row["ManagerId"] = entity.ManagerId.HasValue ? (object) entity.ManagerId  : System.DBNull.Value;
							
				
					row["CurrencyUnitId"] = entity.CurrencyUnitId.HasValue ? (object) entity.CurrencyUnitId  : System.DBNull.Value;
							
				
					row["Name"] = entity.Name;
							
				
					row["Description"] = entity.Description;
							
				
					row["DesignPrice"] = entity.DesignPrice.HasValue ? (object) entity.DesignPrice  : System.DBNull.Value;
							
				
					row["AuctualPrice"] = entity.AuctualPrice.HasValue ? (object) entity.AuctualPrice  : System.DBNull.Value;
							
				
					row["IsActive"] = entity.IsActive.HasValue ? (object) entity.IsActive  : System.DBNull.Value;
							
				
					row["IsApprove"] = entity.IsApprove.HasValue ? (object) entity.IsApprove  : System.DBNull.Value;
							
				
					row["IsCurrentProjectPhase"] = entity.IsCurrentProjectPhase.HasValue ? (object) entity.IsCurrentProjectPhase  : System.DBNull.Value;
							
				
					row["Status"] = entity.Status.HasValue ? (object) entity.Status  : System.DBNull.Value;
							
				
					row["Type"] = entity.Type.HasValue ? (object) entity.Type  : System.DBNull.Value;
							
				
					row["FromDate"] = entity.FromDate.HasValue ? (object) entity.FromDate  : System.DBNull.Value;
							
				
					row["ToDate"] = entity.ToDate.HasValue ? (object) entity.ToDate  : System.DBNull.Value;
							
				
					row["RealFromDate"] = entity.RealFromDate.HasValue ? (object) entity.RealFromDate  : System.DBNull.Value;
							
				
					row["RealToDate"] = entity.RealToDate.HasValue ? (object) entity.RealToDate  : System.DBNull.Value;
							
				
					row["ParentPath"] = entity.ParentPath;
							
				
					row["IsCollectItemFromChild"] = entity.IsCollectItemFromChild.HasValue ? (object) entity.IsCollectItemFromChild  : System.DBNull.Value;
							
				
					row["IsStart"] = entity.IsStart.HasValue ? (object) entity.IsStart  : System.DBNull.Value;
							
				
					row["IsFinished"] = entity.IsFinished.HasValue ? (object) entity.IsFinished  : System.DBNull.Value;
							
				
					row["IsBillable"] = entity.IsBillable.HasValue ? (object) entity.IsBillable  : System.DBNull.Value;
							
				
					row["CreationDate"] = entity.CreationDate.HasValue ? (object) entity.CreationDate  : System.DBNull.Value;
							
				
					row["CreationUserId"] = entity.CreationUserId.HasValue ? (object) entity.CreationUserId  : System.DBNull.Value;
							
				
					row["LastModificationDate"] = entity.LastModificationDate.HasValue ? (object) entity.LastModificationDate  : System.DBNull.Value;
							
				
					row["LastModificationUserId"] = entity.LastModificationUserId.HasValue ? (object) entity.LastModificationUserId  : System.DBNull.Value;
							
				
					row["ExchangeRate"] = entity.ExchangeRate.HasValue ? (object) entity.ExchangeRate  : System.DBNull.Value;
							
				
				dataTable.Rows.Add(row);
			}		
			
			// send the data to the server		
			bulkCopy.WriteToServer(dataTable);		
			
			// update back the state
			foreach(RLM.Construction.Entities.ProjectPhase entity in entities)
			{
				if (entity.EntityState != EntityState.Added)
					continue;
			
				entity.AcceptChanges();
			}
		}
				
		/// <summary>
		/// 	Inserts a RLM.Construction.Entities.ProjectPhase object into the datasource using a transaction.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">RLM.Construction.Entities.ProjectPhase object to insert.</param>
		/// <remarks>
		///		After inserting into the datasource, the RLM.Construction.Entities.ProjectPhase object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>	
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Insert(TransactionManager transactionManager, RLM.Construction.Entities.ProjectPhase entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_Insert", _useStoredProcedure);
			
			database.AddOutParameter(commandWrapper, "@ProjectPhaseId", DbType.Int32, 4);
			database.AddInParameter(commandWrapper, "@ParentProjectPhaseId", DbType.Int32, (entity.ParentProjectPhaseId.HasValue ? (object) entity.ParentProjectPhaseId  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ProjectId", DbType.Int32, entity.ProjectId );
			database.AddInParameter(commandWrapper, "@ContractId", DbType.Int32, (entity.ContractId.HasValue ? (object) entity.ContractId  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ManagerId", DbType.Int32, (entity.ManagerId.HasValue ? (object) entity.ManagerId  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@CurrencyUnitId", DbType.Int32, (entity.CurrencyUnitId.HasValue ? (object) entity.CurrencyUnitId  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Name", DbType.String, entity.Name );
			database.AddInParameter(commandWrapper, "@Description", DbType.String, entity.Description );
			database.AddInParameter(commandWrapper, "@DesignPrice", DbType.Currency, (entity.DesignPrice.HasValue ? (object) entity.DesignPrice  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@AuctualPrice", DbType.Currency, (entity.AuctualPrice.HasValue ? (object) entity.AuctualPrice  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsActive", DbType.Boolean, (entity.IsActive.HasValue ? (object) entity.IsActive  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsApprove", DbType.Boolean, (entity.IsApprove.HasValue ? (object) entity.IsApprove  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsCurrentProjectPhase", DbType.Boolean, (entity.IsCurrentProjectPhase.HasValue ? (object) entity.IsCurrentProjectPhase  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Status", DbType.Int32, (entity.Status.HasValue ? (object) entity.Status  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@Type", DbType.Int32, (entity.Type.HasValue ? (object) entity.Type  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@FromDate", DbType.DateTime, (entity.FromDate.HasValue ? (object) entity.FromDate  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ToDate", DbType.DateTime, (entity.ToDate.HasValue ? (object) entity.ToDate  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@RealFromDate", DbType.DateTime, (entity.RealFromDate.HasValue ? (object) entity.RealFromDate  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@RealToDate", DbType.DateTime, (entity.RealToDate.HasValue ? (object) entity.RealToDate  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ParentPath", DbType.String, entity.ParentPath );
			database.AddInParameter(commandWrapper, "@IsCollectItemFromChild", DbType.Boolean, (entity.IsCollectItemFromChild.HasValue ? (object) entity.IsCollectItemFromChild  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsStart", DbType.Boolean, (entity.IsStart.HasValue ? (object) entity.IsStart  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsFinished", DbType.Boolean, (entity.IsFinished.HasValue ? (object) entity.IsFinished  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@IsBillable", DbType.Boolean, (entity.IsBillable.HasValue ? (object) entity.IsBillable  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@CreationDate", DbType.DateTime, (entity.CreationDate.HasValue ? (object) entity.CreationDate  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@CreationUserId", DbType.Int32, (entity.CreationUserId.HasValue ? (object) entity.CreationUserId  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@LastModificationDate", DbType.DateTime, (entity.LastModificationDate.HasValue ? (object) entity.LastModificationDate  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@LastModificationUserId", DbType.Int32, (entity.LastModificationUserId.HasValue ? (object) entity.LastModificationUserId  : System.DBNull.Value));
			database.AddInParameter(commandWrapper, "@ExchangeRate", DbType.Int32, (entity.ExchangeRate.HasValue ? (object) entity.ExchangeRate  : System.DBNull.Value));
			
			int results = 0;
			
				
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
					

			entity.ProjectPhaseId = (System.Int32) database.GetParameterValue(commandWrapper, "@ProjectPhaseId");						
			
			
			entity.AcceptChanges();
	
			return Convert.ToBoolean(results);
		}	
		#endregion

		#region Update Methods
				
		/// <summary>
		/// 	Update an existing row in the datasource.
		/// </summary>
		/// <param name="transactionManager"><see cref="TransactionManager"/> object</param>
		/// <param name="entity">RLM.Construction.Entities.ProjectPhase object to update.</param>
		/// <remarks>
		///		After updating the datasource, the RLM.Construction.Entities.ProjectPhase object will be updated
		/// 	to refelect any changes made by the datasource. (ie: identity or computed columns)
		/// </remarks>
		/// <returns>Returns true if operation is successful.</returns>
        /// <exception cref="System.Exception">The command could not be executed.</exception>
        /// <exception cref="System.Data.DataException">The <paramref name="transactionManager"/> is not open.</exception>
        /// <exception cref="System.Data.Common.DbException">The command could not be executed.</exception>
		public override bool Update(TransactionManager transactionManager, RLM.Construction.Entities.ProjectPhase entity)
		{
			SqlDatabase database = new SqlDatabase(this._connectionString);
			DbCommand commandWrapper = StoredProcedureProvider.GetCommandWrapper(database, "dbo.ProjectPhase_Update", _useStoredProcedure);
			
			database.AddInParameter(commandWrapper, "@ProjectPhaseId", DbType.Int32, entity.ProjectPhaseId );
			database.AddInParameter(commandWrapper, "@ParentProjectPhaseId", DbType.Int32, (entity.ParentProjectPhaseId.HasValue ? (object) entity.ParentProjectPhaseId : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ProjectId", DbType.Int32, entity.ProjectId );
			database.AddInParameter(commandWrapper, "@ContractId", DbType.Int32, (entity.ContractId.HasValue ? (object) entity.ContractId : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ManagerId", DbType.Int32, (entity.ManagerId.HasValue ? (object) entity.ManagerId : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@CurrencyUnitId", DbType.Int32, (entity.CurrencyUnitId.HasValue ? (object) entity.CurrencyUnitId : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Name", DbType.String, entity.Name );
			database.AddInParameter(commandWrapper, "@Description", DbType.String, entity.Description );
			database.AddInParameter(commandWrapper, "@DesignPrice", DbType.Currency, (entity.DesignPrice.HasValue ? (object) entity.DesignPrice : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@AuctualPrice", DbType.Currency, (entity.AuctualPrice.HasValue ? (object) entity.AuctualPrice : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsActive", DbType.Boolean, (entity.IsActive.HasValue ? (object) entity.IsActive : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsApprove", DbType.Boolean, (entity.IsApprove.HasValue ? (object) entity.IsApprove : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsCurrentProjectPhase", DbType.Boolean, (entity.IsCurrentProjectPhase.HasValue ? (object) entity.IsCurrentProjectPhase : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Status", DbType.Int32, (entity.Status.HasValue ? (object) entity.Status : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@Type", DbType.Int32, (entity.Type.HasValue ? (object) entity.Type : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@FromDate", DbType.DateTime, (entity.FromDate.HasValue ? (object) entity.FromDate : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ToDate", DbType.DateTime, (entity.ToDate.HasValue ? (object) entity.ToDate : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@RealFromDate", DbType.DateTime, (entity.RealFromDate.HasValue ? (object) entity.RealFromDate : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@RealToDate", DbType.DateTime, (entity.RealToDate.HasValue ? (object) entity.RealToDate : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ParentPath", DbType.String, entity.ParentPath );
			database.AddInParameter(commandWrapper, "@IsCollectItemFromChild", DbType.Boolean, (entity.IsCollectItemFromChild.HasValue ? (object) entity.IsCollectItemFromChild : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsStart", DbType.Boolean, (entity.IsStart.HasValue ? (object) entity.IsStart : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsFinished", DbType.Boolean, (entity.IsFinished.HasValue ? (object) entity.IsFinished : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@IsBillable", DbType.Boolean, (entity.IsBillable.HasValue ? (object) entity.IsBillable : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@CreationDate", DbType.DateTime, (entity.CreationDate.HasValue ? (object) entity.CreationDate : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@CreationUserId", DbType.Int32, (entity.CreationUserId.HasValue ? (object) entity.CreationUserId : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@LastModificationDate", DbType.DateTime, (entity.LastModificationDate.HasValue ? (object) entity.LastModificationDate : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@LastModificationUserId", DbType.Int32, (entity.LastModificationUserId.HasValue ? (object) entity.LastModificationUserId : System.DBNull.Value) );
			database.AddInParameter(commandWrapper, "@ExchangeRate", DbType.Int32, (entity.ExchangeRate.HasValue ? (object) entity.ExchangeRate : System.DBNull.Value) );
			
			int results = 0;
			
			
			if (transactionManager != null)
			{
				results = Utility.ExecuteNonQuery(transactionManager, commandWrapper);
			}
			else
			{
				results = Utility.ExecuteNonQuery(database,commandWrapper);
			}
			
			//Stop Tracking Now that it has been updated and persisted.
			if (DataRepository.Provider.EnableEntityTracking)
				EntityManager.StopTracking(entity.EntityTrackingKey);
			
			
			entity.AcceptChanges();
	
			return Convert.ToBoolean(results);
		}
			
		#endregion
		
		#region Custom Methods
	
		#endregion
	}//end class
} // end namespace
