//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RadColorPicker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadColorPicker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadColorPicker", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ApplyButtonText {
            get {
                return ResourceManager.GetString("ApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blank.
        /// </summary>
        internal static string BlankColorText {
            get {
                return ResourceManager.GetString("BlankColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current Color is {0}).
        /// </summary>
        internal static string CurrentColorText {
            get {
                return ResourceManager.GetString("CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string HSBSliderDragText {
            get {
                return ResourceManager.GetString("HSBSliderDragText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSB.
        /// </summary>
        internal static string HSBTabText {
            get {
                return ResourceManager.GetString("HSBTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string HSVSliderDragText {
            get {
                return ResourceManager.GetString("HSVSliderDragText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSV.
        /// </summary>
        internal static string HSVTabText {
            get {
                return ResourceManager.GetString("HSVTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Color.
        /// </summary>
        internal static string NoColorText {
            get {
                return ResourceManager.GetString("NoColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Color.
        /// </summary>
        internal static string PickColorText {
            get {
                return ResourceManager.GetString("PickColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string RGBSlidersDecreaseText {
            get {
                return ResourceManager.GetString("RGBSlidersDecreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string RGBSlidersDragText {
            get {
                return ResourceManager.GetString("RGBSlidersDragText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string RGBSlidersIncreaseText {
            get {
                return ResourceManager.GetString("RGBSlidersIncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Sliders.
        /// </summary>
        internal static string RGBSlidersTabText {
            get {
                return ResourceManager.GetString("RGBSlidersTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Palette.
        /// </summary>
        internal static string WebPaletteTabText {
            get {
                return ResourceManager.GetString("WebPaletteTabText", resourceCulture);
            }
        }
    }
}
